stages:
  - sast
  - sca
  - build
  - test
  - deploy
  - dash
sonarqube-check:
  stage: sast
  image: maven:3.9.3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: 0  
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_TOKEN}
  allow_failure: true 
  artifacts:
    reports:
      sonarqube: gl-sast-report.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always