stages:
  - build
  - sast
  - sca
  - test
  - deploy
  - dash

build:
  stage: build
  image: maven:3.9.3-eclipse-temurin-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: 0  
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - .sonar/cache
  script:
    - export MAVEN_OPTS=""
    - mvn clean install -DskipTests=true -Dexec.skip=true
  artifacts:
    paths:
      - target/*.jar
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

sonarqube-check:
  stage: sast
  image: maven:3.9.3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: 0  
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=https://8e4d-2001-861-5d00-f9c0-9102-1a68-52e-a3ec.ngrok-free.app -Dsonar.login=${SONAR_TOKEN}
  allow_failure: true 
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

trivy-scan:
  stage: sca
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 0 --severity HIGH,CRITICAL . --ignore-unfixed --format table --output trivy.txt
  artifacts:
    paths:
      - trivy.txt  
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always