stages:
  - sast
  - sca
  - build
  - deploy
  - dash

sonarqube-check:
  stage: sast
  image: maven:3.9.3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: 0  
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=https://5b8d-2001-861-5d00-f9c0-e3cc-3394-8cf5-dffa.ngrok-free.app  -Dsonar.login=${SONAR_TOKEN}
  allow_failure: true 
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

trivy-scan:
  stage: sca
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --exit-code 0 --severity HIGH,CRITICAL . --ignore-unfixed --format table --output trivy.txt
  artifacts:
    paths:
      - trivy.txt  
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker save -o docker-image.tar ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  when: manual
  artifacts:
    paths:
      - docker-image.tar
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker load -i docker-image.tar
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker run -d --name ${CI_PROJECT_NAME} -p 8080:8080 ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker ps
    - docker logs ${CI_PROJECT_NAME}
  when: manual
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always      