apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    k8s-app: myapp
  name: myapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: myapp
